// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOMC2MBl3s9kATj75uSgARylgw7Sdg_sI',
    appId: '1:918863462295:web:e74a679b876703ccb40ed2',
    messagingSenderId: '918863462295',
    projectId: 'ardent-dream-375422',
    authDomain: 'ardent-dream-375422.firebaseapp.com',
    storageBucket: 'ardent-dream-375422.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOyL8xnm15xiVPQrtsRj3pZC7Wt48Noo',
    appId: '1:918863462295:android:df2bce4ee4eef3b9b40ed2',
    messagingSenderId: '918863462295',
    projectId: 'ardent-dream-375422',
    storageBucket: 'ardent-dream-375422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Vh36RHZEWHtFWSWNC-XHaH_cWmHTfMU',
    appId: '1:918863462295:ios:3fa34ec189128901b40ed2',
    messagingSenderId: '918863462295',
    projectId: 'ardent-dream-375422',
    storageBucket: 'ardent-dream-375422.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Vh36RHZEWHtFWSWNC-XHaH_cWmHTfMU',
    appId: '1:918863462295:ios:4f0e1715cd423c60b40ed2',
    messagingSenderId: '918863462295',
    projectId: 'ardent-dream-375422',
    storageBucket: 'ardent-dream-375422.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
