// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRy0g7zRvhR2w7wAe7J2YkXBvozpnM-wk',
    appId: '1:411561204262:web:44566f095b53ddd34164e7',
    messagingSenderId: '411561204262',
    projectId: 'fluuter-sets',
    authDomain: 'fluuter-sets.firebaseapp.com',
    storageBucket: 'fluuter-sets.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZO4BKQOgTx1oQjsPh4EgDSW7pdydd6A',
    appId: '1:411561204262:android:36d38cc1ffbf56c24164e7',
    messagingSenderId: '411561204262',
    projectId: 'fluuter-sets',
    storageBucket: 'fluuter-sets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHgw4SIQtfyIqDjnoKqH3eNkAxf30kO8',
    appId: '1:411561204262:ios:248f5c9f4bff5b6e4164e7',
    messagingSenderId: '411561204262',
    projectId: 'fluuter-sets',
    storageBucket: 'fluuter-sets.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdHgw4SIQtfyIqDjnoKqH3eNkAxf30kO8',
    appId: '1:411561204262:ios:ccb8c09b5f2ab6414164e7',
    messagingSenderId: '411561204262',
    projectId: 'fluuter-sets',
    storageBucket: 'fluuter-sets.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
